Add the incoming mapper to the integration instance
badarsebard/terraform-provider-xsoar pull request #2
Opened 2022-02-22 13:51 UTC by franciscosd

Whilst we considered adding variables like the incoming mapper id in the config map, we came to the conclusion that is was more logical to add it as a separate variable inside the resource.

In terms of testing of the code, we tested the creating, updating and destruction of integration instance resources with and without the incoming mapper id.

Good thing to be aware of, is that XSOAR lacks input validation in the API. This means that you can provide invalid incoming mapper id's, but you can also provide fields that XSOAR says it requires - whilst it does not return errors if you don't provide it. We've already started a conversation about this with our Palo Alto contacts, as we think this should be fixed in XSOAR - and we should not be required to add such validation into the Terraform provider.

2022-02-22 14:22 UTC, jrauen commented on xsoar/resource_integration_instance.go
> +		IncomingMapperId:  types.String{},
This value should be available from the API response

2022-02-24 19:20 UTC, badarsebard requested changes

2022-02-24 19:20 UTC, badarsebard commented on xsoar/data_source_integration_instance.go
> +		IncomingMapperId:  types.String{Value: integration["incomingMapperId"].(string)},
This has the potential to panic if the value of the `interface{}` is `nil`. When using type conversion in `nil` it's suggested to use multiple assignment and verify the result.

```go
incomingMapperId, ok := integration["incomingMapperId"].(string)
if ok {
    result.incomingMapperId = types.String{Value: incomingMapperId}
} else {
    result.incomingMapperId = types.String{Null: true}
}
```

2022-02-24 19:20 UTC, badarsebard commented on xsoar/resource_integration_instance.go
> +		IncomingMapperId:  types.String{Value: integration["incomingMapperId"].(string)},
Same as above

2022-02-24 19:20 UTC, badarsebard commented on xsoar/resource_integration_instance.go
> +		IncomingMapperId:  types.String{Value: integration["incomingMapperId"].(string)},
Same as above

2022-02-24 19:20 UTC, badarsebard commented on xsoar/resource_integration_instance.go
> +		IncomingMapperId:  types.String{Value: integration["incomingMapperId"].(string)},
Same as above

2022-02-24 19:20 UTC, badarsebard commented on xsoar/resource_integration_instance.go
> +		IncomingMapperId:  types.String{Value: integration["incomingMapperId"].(string)},
Same as above

2022-04-26 18:10 UTC, fancybear-dev commented
The incoming mapper id should be OK now. Have tested it quite extensively, and had no issues.

2022-04-27 15:27 UTC, jrauen approved these changes

2022-04-27 15:28 UTC, merged